name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEYS }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Create release folder on server
        run: |
          RELEASE=$(date +%Y%m%d_%H%M%S)
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
          "mkdir -p /app/my-site/releases/$RELEASE"

      - name: Sync files to VPS (rsync)
        run: |
          rsync -avz ./ \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/app/my-site/releases/${{ env.RELEASE }}/

      - name: Update current symlink
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
          "ln -sfn /app/my-site/releases/${{ env.RELEASE }} /app/my-site/current"

      - name: Reload Nginx
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
          "systemctl reload nginx"
